spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animorise
    username: postgres
    password: AMINOX1999
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # Disable open-in-view to avoid performance issues
  docker:
    compose:
      enabled: false
  liquibase:
    enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8088

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 36000000000 # 36000000000 milliseconds = 10000 hours (adjust as needed)